# Project-wide Gradle settings.
org.gradle.java.home=/home/z/jdk-17
org.gradle.jvmargs=-Xmx2048m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.configuration-cache=false
kotlin.code.style=official
android.disallowKotlinSourceSets=false
android.useAndroidX=true
org.gradle.daemon=false
org.gradle.caching=true
